# -*- coding: utf-8 -*-
"""llm_finetuning_project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EMuiOK7abd-_-pvZctZwdp-Zc3eTHNhp

Install Required Libraries
"""

!pip install -q transformers datasets peft accelerate bitsandbytes
!pip install -U bitsandbytes accelerate

"""Import Libraries"""

import torch
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
from peft import LoraConfig, get_peft_model

"""Create a Simple Dataset"""

data = {
    "text": [
        "Question: What is machine learning? Answer: Machine learning is a field of AI that allows systems to learn from data.",
        "Question: What is deep learning? Answer: Deep learning is a subset of machine learning using neural networks.",
        "Question: What is overfitting? Answer: Overfitting happens when a model memorizes training data instead of learning patterns.",
        "Question: What is RAG? Answer: Retrieval Augmented Generation combines LLMs with external knowledge retrieval."
    ]
}

dataset = Dataset.from_dict(data)

"""Load Lightweight Model"""

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto"
)

"""Tokenize Dataset

"""

def tokenize(example):
    result = tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

    result["labels"] = result["input_ids"]
    return result

dataset = dataset.map(tokenize)
dataset.set_format(type="torch")
dataset = dataset.map(tokenize)
dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

"""Configure LoRA"""

from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj","v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)
model = get_peft_model(model, lora_config)

"""Training Setup"""

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=1,
    num_train_epochs=1,
    logging_steps=1,
    learning_rate=2e-4,
    fp16=True,
    report_to="none"
)

"""Trainer"""

trainer = Trainer(
    model=model,
    train_dataset=dataset,
    args=training_args
)

trainer.train()

"""Test the Model"""

prompt = "Question: What is machine learning? Answer:"

inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

output = model.generate(**inputs, max_new_tokens=50)

print(tokenizer.decode(output[0]))

"""Save Model"""

model.save_pretrained("fine_tuned_model")
tokenizer.save_pretrained("fine_tuned_model")

"""Load the Fine-Tuned Model"""

from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
adapter_path = "fine_tuned_model"

tokenizer = AutoTokenizer.from_pretrained(base_model)

model = AutoModelForCausalLM.from_pretrained(
    base_model,
    device_map="auto"
)

model = PeftModel.from_pretrained(model, adapter_path)

"""Test the Model

"""

prompt = "Question: What is machine learning? Answer:"

inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

output = model.generate(
    **inputs,
    max_new_tokens=60
)

print(tokenizer.decode(output[0], skip_special_tokens=True))

"""Create an Interactive Chat Loop

"""

while True:
    prompt = input("Ask a question: ")

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    output = model.generate(
        **inputs,
        max_new_tokens=80
    )

    print("\nAnswer:")
    print(tokenizer.decode(output[0], skip_special_tokens=True))

"""Download the Model From Colab"""

from google.colab import files
import shutil

shutil.make_archive("fine_tuned_model", 'zip', "fine_tuned_model")
files.download("fine_tuned_model.zip")